exports.State = function(adapter, obj) {
    adapter.setStateAsync("get.aplwday", obj.DATA.APLWDAY, true);
    adapter.setStateAsync("get.status", obj.DATA.STATUS, true);
    adapter.setStateAsync("get.fdr", obj.DATA.FDR, true);
    adapter.setStateAsync("get.t1", obj.DATA.T1, true);
    adapter.setStateAsync("get.t2", obj.DATA.T2, true);
    adapter.setStateAsync("get.t3", obj.DATA.T3, true);
    adapter.setStateAsync("get.t4", obj.DATA.T4, true);
    adapter.setStateAsync("get.t5", obj.DATA.T5, true);
    adapter.setStateAsync("get.pqt", obj.DATA.PQT, true);
    adapter.setStateAsync("get.in", obj.DATA.IN, true);
    adapter.setStateAsync("get.out", obj.DATA.OUT, true);
    adapter.setStateAsync("get.f1v", obj.DATA.F1V, true);
    adapter.setStateAsync("get.f2v", obj.DATA.F2V, true);
    adapter.setStateAsync("get.f2lf", obj.DATA.F2LF, true);
    adapter.setStateAsync("get.pump", obj.DATA.PUMP, true);
    adapter.setStateAsync("get.dpt", obj.DATA.DPT, true);
    adapter.setStateAsync("get.dp", obj.DATA.DP, true);
    adapter.setStateAsync("get.f1rpm", obj.DATA.F1RPM, true);
    adapter.setStateAsync("get.chrstatus", obj.DATA.CHRSTATUS, true);
};